### ISSUE TITLE
run.only()

### ISSUE THREAD

**Issue by jamesplease** [daliwali/tapdance#3]
A feature I've grown accustomed to in test frameworks is a `.only()` method. The use case is this:

You're working on a library with 1000 tests. You need to add a new feature. It breaks a few tests, but you don't want to add logging to the method that's throwing, because it'll be called a thousand times. So you add a `.only()` to isolate just the failing tests, so that you can add debug logs.

One idea that works is commenting out all of the other tests, but that doesn't seem as efficient.

Would you open to adding a `.only()` to this lib? If not, how do you go about debugging tests when just a few fail among many?

**Comment by daliwali** [comment]
Very late reply: I just split up my tests into small files and run `node test/case.js` on each file individually if I don't want to run everything. `.only` seems convenient but I don't want to add any API.
